name: mythosapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  provider: ^6.1.2
  dio: ^5.7.9
  intl: ^0.19.0
  image_picker: ^1.0.7

  # Map & calendar
  google_maps_flutter: ^2.12.1
  geolocator: ^12.0.0
  table_calendar: ^3.1.2

  # NUEVO: clustering, SVG para marker y preferencias
  google_maps_cluster_manager: ^3.0.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.3.2
  
  # Typography and UI improvements
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  
  # Device permissions and settings
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

  # Abrir "CÃ³mo llegar"
  url_launcher: ^6.3.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
