name: mythosapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  provider: ^6.1.2
  dio: ^5.7.9
  intl: ^0.19.0
  image_picker: ^1.0.7

  # Map & calendar
  google_maps_flutter: ^2.12.1
  geolocator: ^12.0.0
  table_calendar: ^3.1.2

  # NUEVO: clustering, SVG para marker y preferencias
  google_maps_cluster_manager: ^3.0.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.3.2
  


  # Abrir “Cómo llegar”
  url_launcher: ^6.3.0

  #Servicios de firebase utilizados
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^6.2.1

  #Tipografia de google
  google_fonts: ^6.3.1
  
  #Manejador de los links para el otp
  app_links: ^6.4.1
  cloud_firestore: ^6.0.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/LogoV2.png
  android_12:
    image: assets/LogoV2.png
    icon_background_color: "#FFFFFF"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/LogoV2.png"
  min_sdk_android: 21
  remove_alpha_ios: true                   # iOS: elimina fondo blanco que Xcode agrega
  adaptive_icon_background: "#00000000"  # Android: mantiene fondo transparente
  adaptive_icon_foreground: "assets/LogoV2.png"

flutter:
  uses-material-design: true

  assets:
  - assets/
